(use-package neotree
 :ensure t
 :defer t)
(use-package dockerfile-mode
 :ensure t
 :defer t)
(use-package purescript-mode
 :ensure t
 :defer t)
(use-package less-css-mode
 :ensure t
 :defer t)
(use-package flycheck-pyflakes
 :ensure t
 :defer t)
(use-package exec-path-from-shell
 :ensure t
 :defer t)
(use-package js2-mode
 :ensure t
 :defer t)
(use-package vue-mode
 :ensure t
 :defer t)
(use-package elm-mode
 :ensure t
 :defer t)
(use-package jsx-mode
 :ensure t
 :defer t)
(use-package scala-mode
 :ensure t
 :defer t)
(use-package yaml-mode
 :ensure t
 :defer t)
(use-package markdown-mode
 :ensure t
 :defer t)
(use-package flx-ido
 :ensure t
 :defer t)
(use-package nix-mode
 :ensure t
 :defer t)

(use-package solarized-theme
  :ensure t)
