#! /bin/sh

bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config top_padding         24

bspc config normal_frame_opacity        0.0
bspc config focused_frame_opacity       0.05

if [ `xrandr -q | grep " connected" | wc -l` -eq "2" ]; then
  if [ `xrandr -q | grep "LVDS1 connected" | wc -l` -eq "1" ]; then
    # Laptop
    echo "LAPTOP"
    bspc monitor LVDS1 -d I II III IV V
    bspc monitor HDMI1 -d VI VII VIII IX X
  else
    if [ `xrandr -q | grep "HDMI1 connected" | wc -l` -eq "1" ]; then
      # Home
      echo "HOME"
      bspc monitor VGA1 -d 2 4 6 8 10
      bspc monitor HDMI1 -d 1 3 5 7 9
    else
      # Work
      echo "WORK"
      bspc monitor DVI-1 -d I II V VI IX X
      bspc monitor DVI-0 -d III IV VII VIII

      # Work requires synergy
      synergys -c ~/.quicksynergy/synergy.conf &
    fi
  fi
else
  # Fallback
  echo "FALLBACK"
  bspc monitor -d I II III IV V VI VII VIII IX X
fi

bspc rule -a Gimp follow=on floating=on
bspc rule -a emacs floating=off

bspc config wm_name LG3D
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize

~/.config/bspwm/panel/panel &
