#! /bin/sh

bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config top_padding         24

bspc config normal_frame_opacity        0.0
bspc config focused_frame_opacity       0.05

if [ `xrandr -q | grep " connected" | wc -l` -eq "2" ]; then
  bspc monitor DVI-1 -d I II V VI IX X
  bspc monitor DVI-0 -d III IV VII VIII
else
  bspc monitor -d I II III IV V VI VII VIII IX X
fi

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a "MPLAB X IDE v3.00" floating=on

panel &
