#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
setopt clobber

# Customize to your needs...

export TERM='xterm-256color'

export GIT_EDITOR="vim"

export JAVA_HOME="/usr/lib/jvm/java-8-openjdk"
export ANDROID_SDK_HOME="/opt/android-sdk/"
export PANEL_FIFO="/tmp/panel_fifo"

if [ -e $HOME/.rbenv/ ]; then
  export PATH="$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init -)"
fi

if [ -e $HOME/.config/bspwm ]; then
  export PATH="$HOME/.config/bspwm/panel/:$PATH"
fi

if [ -e $HOME/bin ]; then 
  export PATH=$PATH:$HOME/bin
fi

if [ -e $HOME/.gem/ruby/2.2.0/bin ]; then
  export PATH=$HOME/.gem/ruby/2.2.0/bin:$PATH
fi

bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

alias m='sudo ruby ~/bin/mounter.rb'
alias suspend='sudo systemctl suspend'

setopt clobber
