# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

source ~/lib/dotconfigs/zshconfigs/rc.zsh

